language: node_js

node_js:

- 8.4.0

after_script:

- scp  -o  StrictHostKeyChecking=no app.js  root@192.168.2.155:/home/www/root/

before_install:

- openssl aes-256-cbc -K $encrypted_7bac67cd0d57_key -iv $encrypted_7bac67cd0d57_iv
  -in  .travis/id_rsa.enc -out id_rsa -d

- mv id_rsa ~/.ssh -f

- chmod 600 ~/.ssh/id_rsa

# 配置 ssh

- eval $(ssh-agent)

- ssh-add ~/.ssh/id_rsa

- cp .travis/ssh_config ~/.ssh/config

